"""empty message

Revision ID: 071544cd0de9
Revises: 2132da2c199d
Create Date: 2023-05-03 01:29:57.285473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071544cd0de9'
down_revision = '2132da2c199d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'song', ['song_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('song_id')

    # ### end Alembic commands ###
