"""empty message

<<<<<<<< HEAD:migrations/versions/2132da2c199d_.py
Revision ID: 2132da2c199d
Revises: 
Create Date: 2023-05-02 16:16:35.407152
========
Revision ID: db575d55379d
Revises: 
Create Date: 2023-05-04 00:18:23.386890
>>>>>>>> fde6af73fb4c4f336770b25a147c018e599c4472:migrations/versions/db575d55379d_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/2132da2c199d_.py
revision = '2132da2c199d'
========
revision = 'db575d55379d'
>>>>>>>> fde6af73fb4c4f336770b25a147c018e599c4472:migrations/versions/db575d55379d_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:migrations/versions/2132da2c199d_.py
========
    op.create_table('coment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=600), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('ad_image', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('version_date', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
>>>>>>>> fde6af73fb4c4f336770b25a147c018e599c4472:migrations/versions/db575d55379d_.py
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=240), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('musicians', 'manager', 'other', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('artist', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('comment')
    op.drop_table('user')
    # ### end Alembic commands ###
